name: CL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set release tag and title
      id: set_release_tag_title
      run: |
        release_tag="0.1.6-PreAlpha"
        release_title="0.1.6 Pre-Alpha"
        echo "::set-output name=release_tag::$release_tag"
        echo "::set-output name=release_title::$release_title"
      shell: bash

    - name: Zip folder
      run: |
        sudo apt-get install -y zip
        zip -r ODB.zip ODB
      working-directory: ${{ github.workspace }}

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Update release
      run: |
        release_tag="${{ steps.set_release_tag_title.outputs.release_tag }}"
        release_title="${{ steps.set_release_tag_title.outputs.release_title}"
        
        if gh release view "$release_tag" &>/dev/null; then
          commit_history=$(git log --oneline -n 5 --format="%s" | awk -v ORS='\n\n' '1')
          commit_history="${commit_history%\n\n}"
          gh release edit "$release_tag" --title "$release_title" --notes "Commit history:\n\n$commit_history"
        else
          commit_history=$(git log --oneline -n 5 --format="%s" | awk -v ORS='\n\n' '1')
          commit_history="${commit_history%\n\n}"
          gh release create "$release_tag" ./ODB.zip --title "$release_title" --prerelease --notes "Commit history:\n\n$commit_history"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
