name: Push Releases

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Get latest release tag
      id: get_latest_release_tag
      run: |
        echo "::set-output name=release_tag::$(gh release list --limit 1 | awk '{print $1}')"
      shell: bash

    - name: Zip folder
      run: |
        sudo apt-get install -y zip
        zip -r ODB.zip ODB
      working-directory: ${{ github.workspace }}

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Create release
      run: |
        release_tag="${{ steps.get_latest_release_tag.outputs.release_tag }}"
        commit_history=$(git log -5 --graph --oneline)
        changelog=$(cat Changelog.md)

        if gh release view "$release_tag" &>/dev/null; then
          gh release delete "$release_tag" --yes
        fi

        gh release create "$release_tag" ./ODB.zip --title "$release_tag" --notes "$changelog"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
